apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-amchrnpv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-amchrnpv:de763f4daa3e98daf33b2d91c57570471459c04a@sha256:aa8b9e261828efced4545ed0e0715577d0193fd287dad4fb8742aef7b812a98c
        name: container-image  
